"""Add membership_type to users

Revision ID: afd727485fdf
Revises: 2038ea8ea416
Create Date: 2025-01-21 05:28:53.980578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd727485fdf'
down_revision: Union[str, None] = '2038ea8ea416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('membership_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'membership_type')
    # ### end Alembic commands ###
